# Generated by Django 4.2.7 on 2023-12-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoclient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('namePoint', models.CharField(max_length=250, null=True)),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('typeInstr', models.CharField(max_length=250)),
                ('axis', models.CharField(max_length=250)),
                ('idObj', models.IntegerField()),
                ('color', models.CharField(max_length=250, null=True)),
                ('lineWidth', models.IntegerField()),
            ],
        ),
    ]
