# Generated by Django 4.2.7 on 2023-12-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoclient', '0002_fromobj'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FromObj',
            new_name='FrontObj',
        ),
    ]
