# Generated by Django 4.2.7 on 2023-12-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoclient', '0003_rename_fromobj_frontobj'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontobj',
            name='build',
            field=models.CharField(default='default', max_length=250, unique=True),
        ),
    ]
