# Generated by Django 4.2.7 on 2023-12-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoclient', '0005_frontobj_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontobj',
            name='axis',
        ),
        migrations.RemoveField(
            model_name='frontobj',
            name='color',
        ),
        migrations.RemoveField(
            model_name='frontobj',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='frontobj',
            name='idObj',
        ),
        migrations.RemoveField(
            model_name='frontobj',
            name='lineWidth',
        ),
        migrations.RemoveField(
            model_name='frontobj',
            name='namePoint',
        ),
        migrations.RemoveField(
            model_name='frontobj',
            name='typeInstr',
        ),
        migrations.RemoveField(
            model_name='frontobj',
            name='x1',
        ),
        migrations.RemoveField(
            model_name='frontobj',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='frontobj',
            name='y1',
        ),
        migrations.RemoveField(
            model_name='frontobj',
            name='y2',
        ),
        migrations.AddField(
            model_name='frontobj',
            name='obj',
            field=models.JSONField(default='default'),
        ),
    ]
